export const PHONE = '+380 63 622 5543'
export const CONTACT_TEXT = 'Свяжитесь с нами, чтобы заказать билет'
export const INFO_1 = '22 НОЯБРЯ'
export const INFO_2 = 'VOLUME CLUB'
export const INFO_3 = '19:00'

export const instagramUrl = 'https://www.instagram.com/marty_tv_/'
export const youtubeUrl = 'https://www.youtube.com/channel/UCL2h5n2vyl25C7DOBDUJ5zQ'
export const vkUrl = 'https://www.youtube.com/channel/UCL2h5n2vyl25C7DOBDUJ5zQ'
export const fbUrl = 'https://www.youtube.com/channel/UCL2h5n2vyl25C7DOBDUJ5zQ'
